source 'http://rubygems.org'

gem 'cucumber' , '~> 2.2.0'
gem 'rspec'
gem 'rake'
gem 'page-object', '~> 2.2.4'
gem 'data_magic'
gem 'cucumber-report-format'
gem 'watir'
gem 'debase'
gem 'report_builder'
